<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form To Add Donation Record</title>
    <link rel="stylesheet" href="donation.css">

</head>
  <nav>
    <a href="publicUserHomePage.php">Home</a>
    <a href="about.html">About Us</a>
    <a href="volunteer.html">Volunteer</a>
    <a href="ContactUs.html">Contact Us</a>
    <a href="addDonationRecordForm.php">Donate</a>
      <a href="systemUserSignUp.php">Sign Up</a>
        <a href="systemUserLogin.php">Login</a>
  </nav>

<?php /* sessions only works with PHP files so need to convert all html to php
session_start();

if (isset($_SESSION['donationSubmitted']) && $_SESSION['donationSubmitted'] === true) {
    // Redirect if user already submitted donation in this session
    header("Location: addDonationRecordForm.php");
    exit;
}

// If you want to allow resubmission, unset the flag here
unset($_SESSION['donationSubmitted']);*/
?>
<body>
    <h2>Add Donation Record Form</h2>
<fieldset>
        <br>
    <form action="addDonationRecordLogic.php" method="post" enctype="multipart/form-data">

        <table width="50%">
        <!--<tr><td>Donation ID:</td><td><input type="text" id="donationID" name="donationID" required</td></tr>-->
<!--Donation ID is auto-generated by the database (AUTO_INCREMENT), so it should not be entered or submitted by the user.
This field is therefore removed from the form to avoid confusion and userinput.-->
        <tr><td>Full Name:</td><td><input type="text" id="donorFullName" name="donorFullName" required></td></tr>
        <tr><td>Email Address:</td><td><input type="text" id="donorEmail" name="donorEmail" required></td></tr>
        <tr><td>Donation Date:</td><td><input type="date" id="donationDate" name="donationDate" required></td></tr>
<tr>
  <td>Donation Frequency:</td>
  <td>
    <label><input type="radio" name="donationFrequency" value="Once-Off" checked> Once-Off</label>
    <label><input type="radio" name="donationFrequency" value="Monthly"> Monthly</label>
  </td>
</tr>

<tr>
  <td>Donation Amount:</td>
  <td>
<div style="margin-bottom: 5px;">
  <!-- Button for preset donation amount R100, identified by unique ID -->
  <button type="button" id="donationAmountBtn100">R100</button>
  
  <!-- Button for preset donation amount R250 -->
  <button type="button" id="donationAmountBtn250">R250</button>
  
  <!-- Button for preset donation amount R500 -->
  <button type="button" id="donationAmountBtn500">R500</button>
  
  <!-- Button for preset donation amount R1000 -->
  <button type="button" id="donationAmountBtn1000">R1000</button>
</div>
    
    <!-- Input field where the donation amount is entered or populated -->
    <input type="number" id="donationAmount" name="donationAmount" step="0.01" min="1" required placeholder="Enter amount">
    <!-- include attribute step="0" to allow decimal; if not change step="1"to ensure that no decimals are allowed. Included min="1" to prevent zero or negative amounts.-->
  
  </td>
</tr>

        <tr>
        <td>Donation Cause Type</td> <!--Gather more information from Makhanda SPCA on current and future campiagns to tailor it-->
        <td><select id="donationCauseType" name="donationCauseType" required>
            <option value="">None</option>
            <option value="General Support">General Support</option>
            <option value="Tick and Flea Treatment">Tick and Flea Treatment</option>
            <option value="Puppy Packs">Puppy Packs</option>
            <option value="Relief for Dogs and Cats">Relief for Dogs and Cats</option>
            <option value="Donkey Upliftment Project">Donkey Upliftment Project</option>
        </select></td>
        </tr>
        
        <tr>

  <td>Choose Suitable Payment Method:</td>
  <td>
      <label><input type="radio" name="paymentMethod" value="visa_card" required> Visa Card </label><br>
      <label><input type="radio" name="paymentMethod" value="paypal"> PayPal</label><br>
      <label><input type="radio" name="paymentMethod" value="bank_account"> Bank Account</label>
  </td>
</tr>
        <tr><td>Donation Notes/ Other:</td>
            <td><input type="text" id="donationNotes" name="donationNotes"></td>
        </tr>
 <tr>
  <td>
    <input type="checkbox" id="acknowledgementOptIn" name="acknowledgementOptIn" value="1">
    I would like to receive an acknowledgement.
  </td>
</tr>

<tr>
  <td>
    <input type="checkbox" id="termsAccepted" name="termsAccepted" value="1" required>
    I agree to the <a href="donationTerms.html" target="_blank">Terms and Conditions</a>.
  </td>
</tr>
        <tr>
            <td><input type="submit" value=" Donate"></td>
        </tr>

        </table>
    </form>
</fieldset>
</body>
<script src="donation.js"></script>
</html>